name: app19022019
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^3.0.0
  http: ^0.12.0+1
  key_value_store: ^1.0.0
  reselect: ^0.4.0
  flutter_redux: ^0.5.3
  key_value_store_flutter: ^1.0.0
  flutter_secure_storage: ^3.2.0
  flutter_youtube: "^1.1.4"
  flutter_tts: ^0.2.4
  audioplayers: ^0.10.0
  page_transition: ^1.0.9
  flutter_swiper: ^1.1.6
  flare_flutter: ^1.3.6





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/audio/incorrect.mp3

   - assets/star-pattern.png
   - assets/book.png
   - assets/background.jpg
   - assets/man.png
   - assets/man-min.png
   - assets/woman.png
   - assets/woman-min.png
   - assets/programación-min.png
   - assets/matemáticas-min.png
   - assets/escritura-min.png
   - assets/arte-min.png
   - assets/lectura-min.png
   - assets/background-drawer.jpg
   - assets/user-min.png
   - assets/video.jpg

   - assets/img100X100/abeja-min.png
   - assets/img100X100/aceite-min.png
   - assets/img100X100/aéreo-min.png
   - assets/img100X100/aeropuerto-min.png
   - assets/img100X100/aguacate-min.png
   - assets/img100X100/agua-min.png
   - assets/img100X100/albañil-min.png
   - assets/img100X100/aldea-min.png
   - assets/img100X100/anillo-min.png
   - assets/img100X100/antiguo-min.png
   - assets/img100X100/apio-min.png
   - assets/img100X100/aprender-min.png
   - assets/img100X100/arcoiris-min.png
   - assets/img100X100/ardilla-min.png
   - assets/img100X100/arpa-min.png
   - assets/img100X100/arte-min.png
   - assets/img100X100/avión-min.png
   - assets/img100X100/azul-min.png
   - assets/img100X100/bailar-min.png
   - assets/img100X100/baile-min.png
   - assets/img100X100/ballena-min.png
   - assets/img100X100/barco-min.png
   - assets/img100X100/becerro-min.png
   - assets/img100X100/biblia-min.png
   - assets/img100X100/bicicleta-min.png
   - assets/img100X100/bota-min.png
   - assets/img100X100/botella-min.png
   - assets/img100X100/boxeador-min.png
   - assets/img100X100/buque-min.png
   - assets/img100X100/burro-min.png
   - assets/img100X100/caballo-min.png
   - assets/img100X100/cama-min.png
   - assets/img100X100/camión-min.png
   - assets/img100X100/camisa-min.png
   - assets/img100X100/campana-min.png
   - assets/img100X100/carro-min.png
   - assets/img100X100/casa-min.png
   - assets/img100X100/cebolla-min.png
   - assets/img100X100/cigüeñas-min.png
   - assets/img100X100/cine-min.png
   - assets/img100X100/ciudad-min.png
   - assets/img100X100/coco-min.png
   - assets/img100X100/conejo-min.png
   - assets/img100X100/cuidado-min.png
   - assets/img100X100/cuna-min.png
   - assets/img100X100/dado-min.png
   - assets/img100X100/dedo-min.png
   - assets/img100X100/delfín-min.png
   - assets/img100X100/diamante-min.png
   - assets/img100X100/dibujo-min.png
   - assets/img100X100/dinero-min.png
   - assets/img100X100/dinosaurio-min.png
   - assets/img100X100/doctor-min.png
   - assets/img100X100/dona-min.png
   - assets/img100X100/duende-min.png
   - assets/img100X100/dulce-min.png
   - assets/img100X100/edificio-min.png
   - assets/img100X100/elefante-min.png
   - assets/img100X100/elote-min.png
   - assets/img100X100/escalera-min.png
   - assets/img100X100/escoba-min.png
   - assets/img100X100/escritura-min.png
   - assets/img100X100/espejo-min.png
   - assets/img100X100/estrella-min.png
   - assets/img100X100/exacto-min.png
   - assets/img100X100/éxito-min.png
   - assets/img100X100/familia-min.png
   - assets/img100X100/faro-min.png
   - assets/img100X100/feliz-min.png
   - assets/img100X100/fideo-min.png
   - assets/img100X100/fiesta-min.png
   - assets/img100X100/flauta-min.png
   - assets/img100X100/flor-min.png
   - assets/img100X100/foco-min.png
   - assets/img100X100/fósforo-min.png
   - assets/img100X100/francia-min.png
   - assets/img100X100/Francia-min.png
   - assets/img100X100/fresa-min.png
   - assets/img100X100/fruta-min.png
   - assets/img100X100/fuego-min.png
   - assets/img100X100/fuente-min.png
   - assets/img100X100/galleta-min.png
   - assets/img100X100/gallina-min.png
   - assets/img100X100/gato-min.png
   - assets/img100X100/gelatina-min.png
   - assets/img100X100/girasol-min.png
   - assets/img100X100/globo-min.png
   - assets/img100X100/gorra-min.png
   - assets/img100X100/guante-min.png
   - assets/img100X100/guerrero-min.png
   - assets/img100X100/guitarra-min.png
   - assets/img100X100/gusano-min.png
   - assets/img100X100/hacha-min.png
   - assets/img100X100/harina-min.png
   - assets/img100X100/hawaii-min.png
   - assets/img100X100/helado-min.png
   - assets/img100X100/helicóptero-min.png
   - assets/img100X100/héroe-min.png
   - assets/img100X100/hielo-min.png
   - assets/img100X100/hilo-min.png
   - assets/img100X100/hormiga-min.png
   - assets/img100X100/horno-min.png
   - assets/img100X100/hueso-min.png
   - assets/img100X100/huevo-min.png
   - assets/img100X100/idea-min.png
   - assets/img100X100/idioma-min.png
   - assets/img100X100/iglesia-min.png
   - assets/img100X100/iglú-min.png
   - assets/img100X100/iguana-min.png
   - assets/img100X100/imán-min.png
   - assets/img100X100/impresora-min.png
   - assets/img100X100/indio-min.png
   - assets/img100X100/invierno-min.png
   - assets/img100X100/isla-min.png
   - assets/img100X100/jabón-min.png
   - assets/img100X100/jaguar-min.png
   - assets/img100X100/jarrón-min.png
   - assets/img100X100/jaula-min.png
   - assets/img100X100/jefe-min.png
   - assets/img100X100/jirafa-min.png
   - assets/img100X100/joya-min.png
   - assets/img100X100/juego-min.png
   - assets/img100X100/jugo-min.png
   - assets/img100X100/juguete-min.png
   - assets/img100X100/karaoke-min.png
   - assets/img100X100/karate-min.png
   - assets/img100X100/kermés-min.png
   - assets/img100X100/kilo-min.png
   - assets/img100X100/kimono-min.png
   - assets/img100X100/kiosco-min.png
   - assets/img100X100/kiwi-min.png
   - assets/img100X100/koala-min.png
   - assets/img100X100/kung-fu-min.png
   - assets/img100X100/lagarto-min.png
   - assets/img100X100/lago-min.png
   - assets/img100X100/lana-min.png
   - assets/img100X100/lápiz-min.png
   - assets/img100X100/lectura-min.png
   - assets/img100X100/leer-min.png
   - assets/img100X100/leña-min.png
   - assets/img100X100/león-min.png
   - assets/img100X100/libro-min.png
   - assets/img100X100/lima-min.png
   - assets/img100X100/limón-min.png
   - assets/img100X100/lobo-min.png
   - assets/img100X100/loro-min.png
   - assets/img100X100/luna-min.png
   - assets/img100X100/mano-min.png
   - assets/img100X100/mapa-min.png
   - assets/img100X100/mariposa-min.png
   - assets/img100X100/matemáticas-min.png
   - assets/img100X100/medalla-min.png
   - assets/img100X100/mesa-min.png
   - assets/img100X100/mimo-min.png
   - assets/img100X100/minuto-min.png
   - assets/img100X100/molino-min.png
   - assets/img100X100/momia-min.png
   - assets/img100X100/mono-min.png
   - assets/img100X100/monstruo-min.png
   - assets/img100X100/moño-min.png
   - assets/img100X100/mundo-min.png
   - assets/img100X100/muñeco-min.png
   - assets/img100X100/naranja-min.png
   - assets/img100X100/nariz-min.png
   - assets/img100X100/nave-min.jpg
   - assets/img100X100/nave-min.png
   - assets/img100X100/negro-min.png
   - assets/img100X100/nido-min.png
   - assets/img100X100/nieve-min.png
   - assets/img100X100/niña-min.png
   - assets/img100X100/niño-min.png
   - assets/img100X100/noche-min.png
   - assets/img100X100/nota-min.png
   - assets/img100X100/nube-min.png
   - assets/img100X100/nuez-min.png
   - assets/img100X100/ñandú-min.png
   - assets/img100X100/ñoño-min.png
   - assets/img100X100/oficina-min.png
   - assets/img100X100/ojo-min.png
   - assets/img100X100/ola-min.png
   - assets/img100X100/olla-min.png
   - assets/img100X100/oreja-min.png
   - assets/img100X100/oro-min.png
   - assets/img100X100/oso-min.png
   - assets/img100X100/otoño-min.png
   - assets/img100X100/oveja-min.png
   - assets/img100X100/paisaje-min.png
   - assets/img100X100/pájaro-min.png
   - assets/img100X100/palmera-min.png
   - assets/img100X100/pantalla-min.png
   - assets/img100X100/pañuelo-min.png
   - assets/img100X100/paraguas-min.png
   - assets/img100X100/pato-min.png
   - assets/img100X100/payaso-min.png
   - assets/img100X100/pelota-min.png
   - assets/img100X100/pera-min.png
   - assets/img100X100/pie-min.png
   - assets/img100X100/pingüino-min.png
   - assets/img100X100/pino-min.png
   - assets/img100X100/piña-min.png
   - assets/img100X100/piñata-min.png
   - assets/img100X100/pollo-min.png
   - assets/img100X100/portaaviones-min.png
   - assets/img100X100/programación-min.png
   - assets/img100X100/puerta-min.png
   - assets/img100X100/quemar-min.png
   - assets/img100X100/querer-min.png
   - assets/img100X100/querubín-min.png
   - assets/img100X100/queso-min.png
   - assets/img100X100/química-min.png
   - assets/img100X100/quintal-min.png
   - assets/img100X100/rama-min.png
   - assets/img100X100/rana-min.png
   - assets/img100X100/raqueta-min.png
   - assets/img100X100/ratón-min.png
   - assets/img100X100/rayito-min.png
   - assets/img100X100/reloj-min.png
   - assets/img100X100/restart-min.png
   - assets/img100X100/reunión-min.png
   - assets/img100X100/rey-min.jpg
   - assets/img100X100/rey-min.png
   - assets/img100X100/risa-min.png
   - assets/img100X100/rosa-min.png
   - assets/img100X100/rueda-min.png
   - assets/img100X100/sándwich-min.png
   - assets/img100X100/sapo-min.png
   - assets/img100X100/saxofón-min.png
   - assets/img100X100/semáforo-min.png
   - assets/img100X100/serpiente-min.png
   - assets/img100X100/sexualidad-min.png
   - assets/img100X100/silla-min.png
   - assets/img100X100/sirena-min.png
   - assets/img100X100/sol-min.png
   - assets/img100X100/sombrero-min.png
   - assets/img100X100/sombrilla-min.png
   - assets/img100X100/sopa-min.png
   - assets/img100X100/sound-min.png
   - assets/img100X100/sumar-min.png
   - assets/img100X100/tambor-min.png
   - assets/img100X100/taxi-min.png
   - assets/img100X100/taza-min.png
   - assets/img100X100/teléfono-min.png
   - assets/img100X100/tenedor-min.png
   - assets/img100X100/tigre-min.png
   - assets/img100X100/tijera-min.png
   - assets/img100X100/tomate-min.png
   - assets/img100X100/tucán-min.png
   - assets/img100X100/unicornio-min.png
   - assets/img100X100/uniforme-min.png
   - assets/img100X100/universo-min.png
   - assets/img100X100/uno-min.png
   - assets/img100X100/uña-min.png
   - assets/img100X100/urbano-min.png
   - assets/img100X100/uvas-min.png
   - assets/img100X100/vaca-min.png
   - assets/img100X100/vacuna-min.png
   - assets/img100X100/vaso-min.png
   - assets/img100X100/vela-min.png
   - assets/img100X100/ventana-min.png
   - assets/img100X100/verano-min.png
   - assets/img100X100/vestido-min.png
   - assets/img100X100/viento-min.png
   - assets/img100X100/vino-min.png
   - assets/img100X100/volcán-min.png
   - assets/img100X100/vuelo-min.png
   - assets/img100X100/waffle-min.png
   - assets/img100X100/walkman-min.png
   - assets/img100X100/Walter-min.png
   - assets/img100X100/waterpolo-min.png
   - assets/img100X100/webcam-min.png
   - assets/img100X100/web-min.png
   - assets/img100X100/wow-min.png
   - assets/img100X100/wu-min.png
   - assets/img100X100/xilófono-min.png
   - assets/img100X100/yate-min.png
   - assets/img100X100/yema-min.png
   - assets/img100X100/yeso-min.png
   - assets/img100X100/yogurt-min.png
   - assets/img100X100/yoyo-min.png
   - assets/img100X100/yunque-min.png
   - assets/img100X100/zanahoria-min.png
   - assets/img100X100/zapatilla-min.png
   - assets/img100X100/zapato-min.png
   - assets/img100X100/zapote-min.png
   - assets/img100X100/zeta-min.png
   - assets/img100X100/zigzag-min.png
   - assets/img100X100/zoología-min.png
   - assets/img100X100/zoológico-min.png
   - assets/img100X100/zorro-min.png

   - assets/alphabet/letter_h.flr
   - assets/alphabet/letter_R.flr

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
