name: app19022019
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^3.0.0
  http: ^0.12.0+1
  key_value_store: ^1.0.0
  reselect: ^0.4.0
  flutter_redux: ^0.5.3
  key_value_store_flutter: ^1.0.0
  flutter_secure_storage: ^3.2.0
  flutter_youtube: "^1.1.4"
  flutter_tts: ^0.2.4
  audioplayers: ^0.10.0
  page_transition: ^1.0.9
  flutter_swiper: ^1.1.6
  flare_flutter: ^1.3.6
  speech_recognition: ^0.3.0+1
  permission_handler: ^3.0.0






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/audio/
   - assets/flare/
   - assets/img100X100/
   - assets/alphabet/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
